[project]
name = "my_project"
slug = "my-project"  

description = "Order Data Analysis using Preswald"
version = "0.1.0"
entrypoint = "hello.py"  

[dependencies]
preswald = "*"
pandas = "*"
plotly = "*"
